spring:
  datasource:
    continue-on-error: true
    initialization-mode: always
    initialize: true
    password: s3cr3tp4ssw0rd
    url: jdbc:postgresql://172.17.35.92:5432/mi_api
    username: postgres-dev
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
